spring:
  application:
    name: client-order-ribbon
#  security:
#      user:
#        name: "client"
#        password: "client"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: var/log/client-order-ribbon.log
server:
  port: 8766
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
#    metadata-map:
#      user.name:  ${spring.security.user.name}
#      user.password:  ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 5
