spring:
  application:
    name: service-user
  zipkin:
    base-url: http://localhost:9994
  sleuth:
    sampler:
      probability: 1.0
# sleuth.sampler.probability 是监控的百分比，默认的是0.1表示10%,这里给1.0表示全部监控
# spring.zipkin.base-url：是zipkin-server的服务路径
#  security:
#      user:
#        name: "client"
#        password: "client"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: var/log/service-user.log
server:
  port: 8763
eureka:
  instance:
      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health
      prefer-ip-address: true
#      metadata-map:
#        user.name:  ${spring.security.user.name}
#        user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

