spring:
  application:
    name: service-user
  zipkin:
    base-url: http://zipkin-service:9994
  sleuth:
    sampler:
      probability: 1.0
#  security:
#      user:
#        name: "client"
#        password: "client"

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: var/log/service-user.log
server:
  port: 8763
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    hostname: service-user
#      metadata-map:
#        user.name:  ${spring.security.user.name}
#        user.password:  ${spring.security.user.password}

  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

